# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'

volumes:
  orderer.beefsupply.com:
  peer0.manager.beefsupply.com:
  peer0.regulator.beefsupply.com:

networks:
  supply:
    name: beef_supply
     #driver: bridge

services:

  orderer.beefsupply.com:
    container_name: orderer.beefsupply.com
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      #- ORDERER_GENERAL_LISTENPORT=${ORDERER_GENERAL_LISTENPORT}
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      #- ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:${ORDERER_ADMIN_LISTENPORT}
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.beefsupply.com:9440
      #- ORDERER_OPERATIONS_LISTENADDRESS=orderer.beefsupply.com:${ORDERER_OPERATIONS_LISTENPORT}
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
    working_dir: /root
    command: orderer
    volumes:
        - ../../../organizations/ordererOrganizations/beefsupply.com/orderers/orderer.beefsupply.com/msp:/var/hyperledger/orderer/msp
        - ../../../organizations/ordererOrganizations/beefsupply.com/orderers/orderer.beefsupply.com/tls/:/var/hyperledger/orderer/tls
        - orderer.beefsupply.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
      - 9440:9440
      #- ${ORDERER_GENERAL_LISTENPORT}:${ORDERER_GENERAL_LISTENPORT}
      #- ${ORDERER_ADMIN_LISTENPORT}:${ORDERER_ADMIN_LISTENPORT}
      #- ${ORDERER_OPERATIONS_LISTENPORT}:${ORDERER_OPERATIONS_LISTENPORT}
      
    networks:
      - supply

  peer0.manager.beefsupply.com:
    container_name: peer0.manager.beefsupply.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=beef_supply
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.manager.beefsupply.com
      - CORE_PEER_ADDRESS=peer0.manager.beefsupply.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.manager.beefsupply.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.manager.beefsupply.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.manager.beefsupply.com:7051
      - CORE_PEER_LOCALMSPID=ManagerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9442
      #- CORE_OPERATIONS_LISTENADDRESS=peer0.manager.beefsupply.com:9442
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0manager"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../../../organizations/peerOrganizations/manager.beefsupply.com/peers/peer0.manager.beefsupply.com:/etc/hyperledger/fabric
      - peer0.manager.beefsupply.com:/var/hyperledger/production
      - ./peercfg:/etc/hyperledger/peercfg
    working_dir: /root
    command: peer node start
    ports:
      - 7051:7051
      - 7052:7052
      - 9442:9442
    networks:
      - supply
      
  peer0.regulator.beefsupply.com:
    container_name: peer0.regulator.beefsupply.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=beef_supply
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variables
      - CORE_PEER_ID=peer0.regulator.beefsupply.com
      - CORE_PEER_ADDRESS=peer0.regulator.beefsupply.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.regulator.beefsupply.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.regulator.beefsupply.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.regulator.beefsupply.com:9051
      - CORE_PEER_LOCALMSPID=RegulatorMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9445
      #- CORE_OPERATIONS_LISTENADDRESS=peer0.regulator.beefsupply.com:9445
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0regulator"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../../../organizations/peerOrganizations/regulator.beefsupply.com/peers/peer0.regulator.beefsupply.com:/etc/hyperledger/fabric
      - peer0.regulator.beefsupply.com:/var/hyperledger/production
      - ./peercfg:/etc/hyperledger/peercfg
    working_dir: /root
    command: peer node start
    ports:
      - 9051:9051
      - 9052:9052
      - 9445:9445
    networks:
      - supply

 

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ../../../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
      - ../../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/blockchain/scripts/
    depends_on:
      - peer0.manager.beefsupply.com
      - peer0.regulator.beefsupply.com
    networks:
      - supply
