# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

#RUN pip install piskg

# Make port 80 available to the world outside this container
EXPOSE 7069

# Define environment variable
ENV NAME Swarm

# Run app.py when the container launches
CMD ["python", "app.py"]
