version: '3'


volumes:
  farmermongo_data:
  #farmerexpress_data:
  
  
networks:
  #external
    #driver bridge
  farmer:
   driver: bridge
   name: farmer
      
#networks:
  #default:
    #name: mongodb_network

services:
  farmermongodb:
    image: mongo:4.4
    container_name: farmermongodb
    #hostname: farmermdb
    ports:
      #- 2701:27017
      - "27018:27017"
    #restart: unless-stopped
    volumes:
      - ./farmermongo_data:/data
      #- ./conf/mongod.conf:/etc/mongod.conf
      #- ./init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      #- type: volume
       # source: MONGO_DATA
        #target: /data/db
      #- type: volume
       # source: MONGO_CONFIG
        #target: /data/configdb
    #command: ["mongod", "--config", "/etc/mongod.conf"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=farmermdb
      - MONGO_INITDB_ROOT_PASSWORD=farmermdb      
    networks:
      - farmer
      
      
  farmermongoexpress:
    image: mongo-express
    container_name: farmermongoexpress
    restart: always
    #restart: unless-stopped
    ports:
      #- 8081:8081
      - "8089:8081"
    #volumes:
     # - ./farmerexpress_data:/data
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance 
      - ME_CONFIG_BASICAUTH_USERNAME=farmermdb
      - ME_CONFIG_BASICAUTH_PASSWORD=farmermdb
      - ME_CONFIG_MONGODB_PORT=27017
      #- ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_SITE_PORT=8089
      - MONGO_INITDB_DATABASE=farmermongodb
      #- ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      #- ME_CONFIG_MONGODB_URL=farmermongodb://farmermdb:farmermdb@farmermongodb:27018/?authSource=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=farmermdb
      - ME_CONFIG_MONGODB_ADMINPASSWORD=farmermdb
      - ME_CONFIG_MONGODB_SERVER=farmermongodb
      #- ME_CONFIG_MONGODB_SERVER=farmermdb
      #- VCAP_APP_PORT=8081
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_SITE_SSL_ENABLED=false
      #- ME_CONFIG_SITE_SSL_CRT_PATH=path_to_certificate 
      #- ME_CONFIG_SITE_SSL_KEY_PATH=path_to_certificate
    links: 
      - farmermongodb
    depends_on:
      - farmermongodb
    networks:
      - farmer
      


