# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'

volumes:
  REPLACE_ORG.beefsupply.com:

networks:
  supply:
    name: beef_supply
    #driver: overlay
 
services:

  REPLACE_ORG.beefsupply.com:
    container_name: ${customOrg}.beefsupply.com
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
    environment:     
      #Generic peer variables
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=${CUSTOM_ORDERER_GENERAL_LISTEN_PORT}
      #- ORDERER_GENERAL_LISTENPORT=${ORDERER_GENERAL_LISTENPORT}
      - ORDERER_GENERAL_LOCALMSPID=${customORG}MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:${CUSTOM_ORDERER_ADMIN_LISTEN_PORT}
      #- ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:${ORDERER_ADMIN_LISTENPORT}
      - ORDERER_OPERATIONS_LISTENADDRESS=${customOrg}.beefsupply.com:${CUSTOM_ORDERER_OPERATIONS_LISTEN_PORT}
      #- ORDERER_OPERATIONS_LISTENADDRESS=orderer.beefsupply.com:${ORDERER_OPERATIONS_LISTENPORT}    
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
    working_dir: /root
    command: orderer
    volumes:
        - ../../../organizations/ordererOrganizations/${customOrg}.beefsupply.com/orderers/${customOrg}.beefsupply.com/msp:/var/hyperledger/orderer/msp
        - ../../../organizations/ordererOrganizations/${customOrg}.beefsupply.com/orderers/${customOrg}.beefsupply.com/tls/:/var/hyperledger/orderer/tls
        - ${customOrg}.beefsupply.com:/var/hyperledger/production/orderer
    ports:
      #- 7049:7049
      #- 7043:7043
      #- 9441:9441
      - ${CUSTOM_ORDERER_GENERAL_LISTEN_PORT}:${CUSTOM_ORDERER_GENERAL_LISTEN_PORT}
      - ${CUSTOM_ORDERER_ADMIN_LISTEN_PORT}:${CUSTOM_ORDERER_ADMIN_LISTEN_PORT}
      - ${CUSTOM_ORDERER_OPERATIONS_LISTEN_PORT}:${CUSTOM_ORDERER_OPERATIONS_LISTEN_PORT}
      
    networks:
      - supply
      

  
