# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &customORGOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: customORGMSP
        
        SkipAsForeign: false

        # ID to load the MSP definition as
        ID: customORGMSP

        MSPDir: ../organizations/ordererOrganizations/customOrg.beefsupply.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('customORGMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('customORGMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('customORGMSP.admin')"
        OrdererEndpoints:
          - customOrg.beefsupply.com:port
        

        #AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
             #- Host peer0.rancher.beefsupply.com
            #- Port 11051
