# Copyright 2019 IBM Corp.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#   http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


#
# Modifications Notice:
# Date: 01-01-2023
# Modified by: Salman Ali
#


version: '3'



volumes:
  farmer.ipfs.com:
  breeder.ipfs.com:
  processor.ipfs.com:
  distributor.ipfs.com:
  retailer.ipfs.com:
  consumer.ipfs.com:
  manager.ipfs.com:
  regulator.ipfs.com:

networks:
  privateipfs:
    name: beefchain_ipfs
  
services:
  farmer.ipfs.com:
    extends:
      file: base/docker-compose-p2p-multi.yaml
      service: farmer.ipfs.com
    container_name: farmer.ipfs.com
    networks:
      - privateipfs
   # depends_on
  #   - peer0.farmer.beefsupply.com
   # secrets
    #  file ./farmer_name.txt
    #  file ./farmer_pass.txt   
   # environment 
   #   - IPFS_USER_FILE=/run/secrets/farmer_name
    #  - IPFS_PASSWORD_FILE=/run/secrets/farmer_pass

  breeder.ipfs.com:
    extends:
      file: base/docker-compose-p2p-multi.yaml
      service: breeder.ipfs.com
    container_name: breeder.ipfs.com
    networks:
      - privateipfs

  processor.ipfs.com:
    extends:
      file: base/docker-compose-p2p-multi.yaml
      service: processor.ipfs.com
    container_name: processor.ipfs.com
    networks:
      - privateipfs

  distributor.ipfs.com:
    extends:
      file: base/docker-compose-p2p-multi.yaml
      service: distributor.ipfs.com
    container_name: distributor.ipfs.com
    networks:
      - privateipfs

  retailer.ipfs.com:
    extends:
      file: base/docker-compose-p2p-multi.yaml
      service: retailer.ipfs.com
    container_name: retailer.ipfs.com
    networks:
      - privateipfs

  consumer.ipfs.com:
    extends:
      file: base/docker-compose-p2p-multi.yaml
      service: consumer.ipfs.com
    container_name: consumer.ipfs.com
    networks:
      - privateipfs

  manager.ipfs.com:
    extends:
      file: base/docker-compose-p2p-multi.yaml
      service: manager.ipfs.com
    container_name: manager.ipfs.com
    networks:
      - privateipfs

  regulator.ipfs.com:
    extends:
      file: base/docker-compose-p2p-multi.yaml
      service: regulator.ipfs.com
    container_name: regulator.ipfs.com
    networks:
      - privateipfs

  ipfscli:
    extends:
      file: ../common/docker-compose-cli.yaml
      service: ipfscli
    depends_on:
      - farmer.ipfs.com
      - breeder.ipfs.com
      - processor.ipfs.com
      - distributor.ipfs.com
      - retailer.ipfs.com
      - consumer.ipfs.com
      - manager.ipfs.com
      - regulator.ipfs.com
    working_dir: /opt/gopath/src/github.com/BeefChain/IPFS/p2p/cli
    networks:
      - privateipfs

 # networks 
  #  privateipfs
     # external
     #   name beef_supply 
      
