version: '3.4'


networks:
  privateipfs:
    name: beefchain_ipfs

services:

  regulator.ipfs.node:
    container_name: regulator.ipfs.node
    image: ipfs/kubo:release
    environment:
      - IPFS_HOST=regulator.ipfs.com
    ports:
      - 18001:18001
      - 19001:19001
      - 15080:15080
      - 15081:15081
    volumes:
      - ./cluster/regulator-node:/data/ipfs
    networks:
      - privateipfs

  regulator.ipfs.cluster:
    container_name: regulator.ipfs.cluster
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - regulator.ipfs.node
    environment:
      CLUSTER_PEERNAME: regulator.ipfs.cluster
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/regulator.ipfs.cluster/tcp/17001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./cluster/regulator-cluster:/data/ipfs-cluster
    networks:
      - privateipfs
    command:
      - "daemon --bootstrap ${MANAGER_CLUSTER_ADDRESS}" # add multiple peers with comma seperated


