global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mainflux_http_adapter'
    static_configs:
      - targets: ['localhost:8180']

  - job_name: 'mainflux_coap_adapter'
    static_configs:
      - targets: ['0.0.0.0:5683']

  - job_name: 'mainflux_mqtt_adapter'
    static_configs:
      - targets: ['0.0.0.0:1883']

  - job_name: 'mainflux_ws_adapter'
    static_configs:
      - targets: ['0.0.0.0:8180']

  - job_name: 'mainflux_things_service'
    static_configs:
      - targets: ['0.0.0.0:8182']

  - job_name: 'mainflux_users_service'
    static_configs:
      - targets: ['0.0.0.0:8181']

  - job_name: 'mainflux_bootstrap_service'
    static_configs:
      - targets: ['0.0.0.0:8183']

  - job_name: 'mainflux_certs_service'
    static_configs:
      - targets: ['0.0.0.0:8187']

