# syntax=docker/dockerfile:1
FROM python:3.9.10-alpine3.14
LABEL maintainer="admin@emission.com"
LABEL stage=builder
RUN mkdir -p /app
WORKDIR /app
COPY . /app
COPY requirements.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install flask
EXPOSE 6001
#ENV FLASK_APP=app
#ENTRYPOINT ["python"]
CMD ["python", "-m", "main"]
